### ISSUE TITLE
fails with permission denied in subdirectory

### ISSUE THREAD

**Issue by jfairley** [codecov/codecov-bash#28]
In one of our Java apps, we have integration tests for permissions. Long story short, directories get created that are unreadable.

When codecov-bash recursively looks for coverage files, it bombs on these directories. I would expect the script to continue recursing through other directories rather than aborting the entire search.

```
(url) https://codecov.io
(root) .
==> Jenkins CI detected.
==> Running gcov (disable via -X gcov)
  -> gcov in .
find: `./reach-engine-core/target/test/reachengine/scratch/bd9d1975-3c89-4b4a-b87a-3d51dcb79ece': Permission denied
find: `./reach-engine-core/target/test/reachengine/scratch/7f239d14-c036-43b5-8693-221940985df0': Permission denied
==> Searching for coverage reports
find: `./reach-engine-core/target/test/reachengine/scratch/bd9d1975-3c89-4b4a-b87a-3d51dcb79ece': Permission denied
find: `./reach-engine-core/target/test/reachengine/scratch/7f239d14-c036-43b5-8693-221940985df0': Permission denied
Something went wrong with Codecov.io coverage upload.
```

FWIW, I do know about `-s DIR`. I'm going to add this to my CI as a patch, but it interferes with the ease-of-use that I so much like about codecov-bash.

**Comment by jfairley** [comment]
I tried `-s DIR` and it didn't seem to matter. Does this syntax look correct?

```
#!/bin/bash

# upload to codecov
{
  bash <(curl -s https://codecov.io/bash) -t "R-E-D-A-C-T-E-D" -X coveragepy -s "reach-engine-core/target/site/jacoco"
} || {
  echo &quot;Something went wrong with Codecov.io coverage upload.&quot;
}
```

**Comment by stevepeak** [comment]
@jfairley the `-s` argument is used to add new folders where coverage reports may be located. In this case, its not necessary.

This is the first I've seen it failing. I think adding `-readable -prune` to the `find` command should fix this.
Is the repository open source? Here is the uploader I would like to try:

```
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/fd4e06dd33950c6ef1a415cdfe6fac1e53bb5152/codecov)  -t "R-E-D-A-C-T-E-D" -X coveragepy
```

**Comment by jfairley** [comment]
It's not open-source. I'll give it a try, and let you know.

**Comment by jfairley** [comment]
This time it printed nothing after "Searching for coverage reports", but it still threw some sort of error. Last time, I saw those errors a second time.

```
(url) https://codecov.io
(root) .
==> Jenkins CI detected.
==> Running gcov (disable via -X gcov)
  -> gcov in .
find: `./reach-engine-core/target/test/reachengine/scratch/e6b0b3e8-5fa7-4d90-9acc-de0ce89c72b0': Permission denied
find: `./reach-engine-core/target/test/reachengine/scratch/b642aa49-062b-4e41-8e4f-53bbda0d863a': Permission denied
==> Searching for coverage reports
```

**Comment by stevepeak** [comment]
Hey @jfairley sorry for the delay. I'm curious if this is still occuring in the newer releases. I believe we have a flag to ignore permissions issues established.

**Comment by jfairley** [comment]
Yes. Our CI still uses the same bash as commented above, minus the `-s` switch. It still throws.

Is there a new switch that I should enable?

**Comment by stevepeak** [comment]
@jfairley can you run this on the current release. I'm curious what the errors are now.

```
bash <(curl -s https://codecov.io/bash)
```

I'm looking at [this thread](http://stackoverflow.com/questions/762348/how-can-i-exclude-all-permission-denied-messages-from-find) and have implemented [here](https://github.com/codecov/codecov-bash/blob/1a2c031c3fce12e7cfc5aa61bdf62b58747caec7/codecov#L714). Thanks!

**Comment by jfairley** [comment]
I thought I should revisit this issue, so I read through that bash file to see what it does. I understand what you were saying about `-s` being used "to add new folders". Even with `-s`, it still also searches in ".".

I may have found a workaround after reading through that bash file. I'm currently setting a custom project root, and that seems to work.

```
-p "reach-engine-core/target/site/jacoco"
```

I understand that this would also interfere with finding the "codecov.yml" and some other meta files, but I don't have any of those, so I can't see a negative impact based on my repo and what the bash file does today.

If `-s` were updated to _replace_ the search paths rather than append, I could use that.

**Comment by jfairley** [comment]
The other thought I had was whether using a `codecov.yml` would "fix" this by bypassing some of that problematic bash code. I haven't configured a `codecov.yml` for any of my projects yet though, I'm not familiar with its options.

**Comment by stevepeak** [comment]
Hey @jfairley thanks for the details on this. I think your idea of replacing the search paths will work well for this. I'll make the adjustments accordingly.

**Comment by jfairley** [comment]
It doesn't seem this is deployed yet. (I just performed a curl locally.) Could you say when that might be?

**Comment by stevepeak** [comment]
Hey @jfairley just deployed now. Thank you for your patience 👍

**Comment by rsyring** [comment]
I believe this is still a problem.  I recently ran the bash script and this was my output:

```
(venv-system) ubuntu@box100:~/shentel$ bash <(curl -s https://codecov.io/bash) -t <snip token>

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-bb2adfe


==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
find: `./.tox/py27/storage-shentel': Permission denied
==> Searching for coverage reports in:
    + .
    + /tmp/circle-artifacts.ocCY2ux
```

The script returns a "1" exit code and, as you can see, nothing gets uploaded.

However, if I use the Python codecov uploader:

```
(venv-system) ubuntu@box100:~/shentel$ codecov -t <snip token>

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.5

==> Detecting CI provider
    Circle CI Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/ubuntu/shentel -type f -name '*.gcno'  -exec gcov -pb  {} +)
find: `/home/ubuntu/shentel/.tox/py27/storage-shentel': Permission denied
    Error running `find /home/ubuntu/shentel -type f -name '*.gcno'  -exec gcov -pb  {} +`: None
==> Collecting reports
    + /home/ubuntu/shentel/coverage.xml bytes=248685
==> Uploading
    .url https://codecov.io
    .query service=circleci&package=py2.0.5&job=62.0&token=<secret>&build=62.0&branch=2017-updates&commit=de097a38e05c0ca8fefb24a893ea8824fc4eadd3&slug=level12%2Fshentel
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/level12/shentel/commit/de097a38e05c0ca8fefb24a893ea8824fc4eadd3
```
The permission issues are there, but they don't kill the entire script.

Going back to the bash script, if I disable some of the features, the error messages move but the upload still fails.

```
(venv-system) ubuntu@box100:~/shentel$ bash <(curl -s https://codecov.io/bash) -X coveragepy -X gcov -X search -t e3daf3ea-914a-44d9-bf00-78ef252a6e5d -f coverage.xml 

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-bb2adfe


==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> gcov disable
==> Searching for coverage reports in:
    + .
    + /tmp/circle-artifacts.ocCY2ux
    -> Found 1 reports
==> Python coveragepy disabled
==> Detecting git/mercurial file structure
==> Reading reports
    + coverage.xml bytes=248685
find: `./.tox/py27/storage-shentel': Permission denied
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
find: `./.tox/py27/storage-shentel': Permission denied
find: `./.tox/py27/storage-shentel': Permission denied
```

**Comment by stevepeak** [comment]
Gotcha! Solved it by adding `|| echo ''` to the `find` commands

**Comment by rsyring** [comment]
@stevepeak thanks for the quick turnaround, that's encouraging.

**Comment by stevepeak** [comment]
I'm sorry it took so long. I was not fully aware of what the issue was.

Deployed 👍 Let me know if its working properly.

**Comment by rsyring** [comment]
@stevepeak the changes didn't solve the problem :(

```
bash <(curl -s https://codecov.io/bash) -t <snip>


  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-0834ffb


==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
find: `./.tox/py27/storage-shentel': Permission denied
==> Searching for coverage reports in:
    + .
    + /tmp/circle-artifacts.2hrfL33
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./coverage.xml bytes=248755
find: `./.tox/py27/storage-shentel': Permission denied
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
find: `./.tox/py27/storage-shentel': Permission denied
find: `./.tox/py27/storage-shentel': Permission denied
```

**Comment by stevepeak** [comment]
Darn, didnt add it to report fixes. Doing that now. Thank you!

**Comment by stevepeak** [comment]
@rsyring can you try this commit:

```
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/34f4a561ac6c889237f76c123f47be42e4a9b134/codecov)
```

Thank you!

**Comment by rsyring** [comment]
@stevepeak that fixed it, thanks.
